pipeline {
  agent any
  
  stages {	
	  
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage'
			bat label: 'Compilation running',
			script: '''cd Product-Master
			mvn compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'
			bat label: 'Test running',
			script: '''cd Product-Master
			mvn test'''
	       
       		}
   	}

	stage('Jacoco Coverage Report') {
        	steps{
            		jacoco()
		}
	}
       
       stage('SonarQube'){
		steps{
				bat label: '',
				script: '''cd Product-Master
				mvn sonar:sonar \
				-Dsonar.host.url=http://3.228.4.36:9000 \
				-Dsonar.login=1db9a8830c20a4c1e46a5c0e887664eaa96294da'''
			}
   		}
	
	stage('Maven Package'){
		steps{
			echo 'Project packaging stage'
			bat label: 'Project packaging',
			script: '''cd Product-Master
			mvn package'''
		}
	} 		
    
  }
}
